using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


using Microsoft.EntityFrameworkCore;

namespace NACTAM.Models {

	/// <summary>
	/// Model for the crypto currency (also used for the database)
	/// </summary>
	public class CryptoCurrency {
		/// <summary>
		/// Database primary key generated by the database used to identify the currency.
		/// Warning: This is not the API id!
		/// Warning: The id is artificially generated by the database and if lost, cannot be recreated!
		/// </summary>
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int Id { get; set; }
		/// <summary>
		/// Short name of the currency, e.g. BTC
		/// </summary>
		public string ShortName { get; set; }
		/// <summary>
		/// APi id of the currency, e.g. bitcoin
		/// Warning: This is not the database id!
		/// Warning: The id depends on the API and can change when a different API is used!
		/// </summary>
		public string ApiId { get; set; }
		/// <summary>
		/// Name of the currency, e.g. Bitcoin
		/// </summary>
		public string Name { get; set; }
		/// <summary>
		/// URL to the logo of the currency
		/// </summary>
		public string? Logo { get; set; }
		/// <summary>
		/// Exchange rate of the currency
		/// </summary>

		public decimal? Rate { get; set; }
		/// <summary>
		/// Date of the last update of the currency
		/// </summary>
		public DateTime? LastUpdated { get; set; }


	}
}
